#!/usr/bin/env python3
"""
export-runtime-map-data.py

Generates runtime game map JSON files from the canonical source:
  scripts/location_profiles.json  →  src/renderer/data/configs/maps/map_001_beiliang.json

Usage:
  python scripts/export-runtime-map-data.py [--dry-run] [--check]

Options:
  --dry-run   Print what would be written without writing to disk.
  --check     Return exit code 1 if generated output differs from current file.

## Architecture Note
  scripts/location_profiles.json   ← EDIT THIS (single source of truth)
  src/renderer/data/configs/maps/  ← GENERATED FILES — do not hand-edit
"""

import argparse
import json
import sys
from pathlib import Path

# ─────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOCATION_PROFILES_PATH = PROJECT_ROOT / "scripts" / "location_profiles.json"
GAME_MAPS_DIR = PROJECT_ROOT / "src" / "renderer" / "data" / "configs" / "maps"

# Map manifest: maps the asset-manager map_id to the game runtime map config.
# When map_manifest.json exists, it is used; otherwise the built-in table is used.
MAP_MANIFEST_PATH = PROJECT_ROOT / "scripts" / "map_manifest.json"

_DEFAULT_MANIFEST = {
    "maps": {
        "map_001": {
            "game_file": "map_001_beiliang",
            "public_subdir": "beiliang",
            "name": "北凉道",
            "description": "清凉山到葫芦口一线，铁血家国之地",
            "terrain_bg": "/maps/beiliang/terrain_bg.png",
        }
    }
}


def _load_manifest() -> dict:
    if MAP_MANIFEST_PATH.exists():
        with open(MAP_MANIFEST_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    return _DEFAULT_MANIFEST


def _load_location_profiles() -> dict:
    with open(LOCATION_PROFILES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def _icon_url_for_location(location: dict, map_id: str, public_subdir: str) -> str:
    """
    Derive the runtime icon URL for a location.

    Priority:
    1. If location has an icon_path pointing to backend/maps/{map_id}/{file}, convert to
       the deployed public URL: /maps/{public_subdir}/{file}  (icon files)
    2. If icon_path is absent or empty, fall back to a predictable pattern.
    """
    icon_path = location.get("icon_path", "")
    if icon_path:
        p = Path(icon_path)
        filename = p.name
        # Icon files go to src/renderer/public/maps/{public_subdir}/{file}
        # which is served as /maps/{public_subdir}/{file}
        # But we might also have a specific icon in the beiliang subdir
        # (e.g. icon_01_qingliangshan.png)
        # Use the beiliang subdir path for deployed icons if not already absolute.
        if filename.startswith("icon_"):
            return f"/maps/{public_subdir}/{filename}"
        # Fallback: use generic scene_{n}.png paths
        return f"/maps/{map_id}/{filename}"
    return ""


def _backdrop_url_for_location(location: dict, map_id: str, public_subdir: str) -> str:
    """Derive the runtime backdrop URL for a location."""
    backdrop_path = location.get("backdrop_path", "")
    if backdrop_path:
        p = Path(backdrop_path)
        filename = p.name
        return f"/maps/{map_id}/{filename}"
    return f"/maps/{public_subdir}/terrain_bg.png"


def generate_map_config(map_id: str, map_data: dict, manifest_entry: dict) -> dict:
    """
    Convert one entry from location_profiles.json into the game runtime map JSON.

    The game runtime map JSON format mirrors the existing map_001_beiliang.json.
    Fields kept:
      map_id, name, description, background_image, locations[]
    Each location keeps:
      location_id, name, icon_image, backdrop_image, position, scene_ids, unlock_conditions
    """
    public_subdir = manifest_entry["public_subdir"]
    terrain_bg = manifest_entry.get("terrain_bg", f"/maps/{public_subdir}/terrain_bg.png")

    locations = []
    for loc in map_data.get("scenes", []):  # "scenes" is the key in location_profiles.json
        location_id = loc.get("id", "")
        icon_url = _icon_url_for_location(loc, map_id, public_subdir)
        backdrop_url = _backdrop_url_for_location(loc, map_id, public_subdir)
        locations.append({
            "location_id": location_id,
            "name": loc.get("name", ""),
            "icon_image": icon_url,
            "backdrop_image": backdrop_url,
            "position": loc.get("position", {"x": 0.5, "y": 0.5}),
            "scene_ids": loc.get("scene_ids", []),
            "unlock_conditions": loc.get("unlock_conditions", {}),
        })

    return {
        "_generated": "DO NOT EDIT — generated by scripts/export-runtime-map-data.py from scripts/location_profiles.json",
        "map_id": f"{map_id}_{manifest_entry['game_file'].replace(map_id + '_', '')}",
        "name": manifest_entry.get("name", map_data.get("name", "")),
        "description": manifest_entry.get("description", ""),
        "background_image": terrain_bg,
        "locations": locations,
    }


def _check_icon_override(manifest_entry: dict, current_locations: list, new_locations: list) -> list:
    """
    When checking consistency, some icon/backdrop URLs may have been manually set
    in the existing game map JSON to a more specific value (e.g. icon_01_qingliangshan.png
    vs. scene_001.png from the generated default). Preserve those manual overrides.
    This function returns new_locations with manual icon/backdrop overrides preserved.
    """
    # Build lookup of existing location icon/backdrop values
    current_by_id = {l["location_id"]: l for l in current_locations}
    result = []
    for loc in new_locations:
        lid = loc["location_id"]
        if lid in current_by_id:
            existing = current_by_id[lid]
            # If the existing icon/backdrop looks more specific (not empty, not a fallback),
            # keep it. This preserves manually tuned paths.
            updated = dict(loc)
            if existing.get("icon_image"):
                updated["icon_image"] = existing["icon_image"]
            if existing.get("backdrop_image"):
                updated["backdrop_image"] = existing["backdrop_image"]
            result.append(updated)
        else:
            result.append(loc)
    return result


def run(dry_run: bool = False, check: bool = False) -> int:
    profiles = _load_location_profiles()
    manifest = _load_manifest()

    all_ok = True
    for map_id, manifest_entry in manifest.get("maps", {}).items():
        map_data = profiles.get("maps", {}).get(map_id)
        if not map_data:
            print(f"[WARN] map_id '{map_id}' in manifest but not in location_profiles.json — skipping.")
            continue

        game_file = manifest_entry["game_file"]
        out_path = GAME_MAPS_DIR / f"{game_file}.json"

        new_config = generate_map_config(map_id, map_data, manifest_entry)

        # If the file exists, preserve existing icon/backdrop overrides
        if out_path.exists():
            with open(out_path, "r", encoding="utf-8") as f:
                current = json.load(f)
            current_locs = current.get("locations", [])
            new_config["locations"] = _check_icon_override(manifest_entry, current_locs, new_config["locations"])

        new_text = json.dumps(new_config, ensure_ascii=False, indent=2)

        if check:
            if out_path.exists():
                existing_text = out_path.read_text(encoding="utf-8")
                if existing_text.strip() != new_text.strip():
                    print(f"[DIFF] {out_path} differs from what would be generated.")
                    all_ok = False
                else:
                    print(f"[OK]   {out_path} is up to date.")
            else:
                print(f"[MISS] {out_path} does not exist — would be created.")
                all_ok = False
        elif dry_run:
            print(f"[DRY-RUN] Would write {out_path}:")
            print(new_text[:500] + "..." if len(new_text) > 500 else new_text)
        else:
            GAME_MAPS_DIR.mkdir(parents=True, exist_ok=True)
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(new_text)
            print(f"[WRITTEN] {out_path}")

    return 0 if all_ok else 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dry-run", action="store_true", help="Print output without writing files.")
    parser.add_argument("--check", action="store_true", help="Exit 1 if output differs from current files.")
    args = parser.parse_args()
    sys.exit(run(dry_run=args.dry_run, check=args.check))
